<?php

namespace RCPCommbank;

use RCP_Payment_Gateway;
use RCP_Member;
use RCP_Payments;

class Gateway extends RCP_Payment_Gateway {

	/**
	 * Initialize the Payment gateway
	 *
	 * @since  1.0.0
	 *
	 * @author Tanner Moushey
	 */
	public function init() {
		$this->supports[] = 'one-time';
		$this->supports[] = 'fees';

		// add any errors generated by the form
		if ( isset( $_GET['commbank-error'], $_GET['message'] ) ) {
			rcp_errors()->add( 'commbank-error', wp_unslash( urldecode( $_GET['message'] ) ), 'register' );
		}
	}

	/**
	 * Get the endpoint for the request
	 *
	 * @param string $merchant_id
	 * @param int $order_id
	 * @param string $transaction_id
	 *
	 * @since  1.0.0
	 *
	 * @return string
	 * @author Tanner Moushey
	 */
	public static function get_endpoint( $merchant_id, $order_id, $transaction_id ) {
		$version     = '44';
		$endpoint    = sprintf( 'https://paymentgateway.commbank.com.au/api/rest/version/%s/merchant/%s/order/%s/transaction/%s', absint( $version ), urlencode( $merchant_id ), absint( $order_id ), urlencode( substr( $transaction_id, 0, 40 ) ) );

		return $endpoint;
	}

	/**
	 * Process registration
	 *
	 * @access public
	 * @since  1.0.0
	 * @return void
	 */
	public function process_signup() {
		global $rcp_options;

		/**
		 * @var RCP_Payments $rcp_payments_db
		 */
		global $rcp_payments_db;

		$merchant_id   = isset( $rcp_options['rcpcommbank_merchant_id'] ) ? $rcp_options['rcpcommbank_merchant_id'] : '' ;
		$merchant_pass = isset( $rcp_options['rcpcommbank_password'] ) ? $rcp_options['rcpcommbank_password'] : '' ;
		$member        = new RCP_Member( $this->user_id );

		// set the form data
		$formData = array(
			'apiOperation'  => 'PAY',
			'sourceOfFunds' => array(
				'type'     => 'CARD',
				'provided' => array(
					'card' => array(
						'number'       => absint( $_POST['rcp_card_number'] ),
						'expiry'       => array(
							'month' => absint( $_POST['rcp_card_exp_month'] ),
							'year'  => absint( substr( $_POST['rcp_card_exp_year'], 2, 2 ) ),
						),
						'securityCode' => absint( $_POST['rcp_card_cvc'] ),
						'nameOnCard'   => sanitize_text_field( $_POST['rcp_card_name'] ),
					),
				),
			),
			'order'         => array(
				'amount'   => rcp_get_registration()->get_total(),
				'currency' => $rcp_options['currency'],
			),
		);

		// encode data and get url endpoint
		$request_data = json_encode( $formData );
		$request_URL  = self::get_endpoint( $merchant_id, $this->payment->id, rcp_get_subscription_name( $this->subscription_id ) );

		$response = wp_remote_request( $request_URL, array(
			'method'  => 'PUT',
			'headers' => array(
				'Authorization' => 'Basic ' . base64_encode( sprintf( 'merchant.%s:%s', $merchant_id, $merchant_pass ) ),
			),
			'body'    => $request_data,
		) );

		$body = json_decode( wp_remote_retrieve_body( $response ) );

		// handle any errors
		if ( empty( $body->result ) || 'SUCCESS' != $body->result ) {

			// define the redirect page
			if ( ! $redirect = get_user_meta( $member->ID, 'registration_page', true ) ) {
				if ( isset( $rcp_options['registration_page'] ) ) {
					$redirect = get_permalink( $rcp_options['registration_page'] );
				} else {
					$redirect = get_home_url();
				}
			}

			$result  = isset( $body->result ) ? $body->result : 'ERROR';
			$message = __( 'Something went wrong, please try again.', rcpcommbank()->get_id() );

			// add any error messages
			switch( strtolower( $result ) ) {
				case 'error' :

					if ( isset( $body->error->explanation ) ) {
						$message = $body->error->explanation;
					}

					break;

				case 'failure' :

					if ( ! isset( $body->response->gatewayCode ) ) {
						break;
					}

					switch ( strtolower( $body->response->gatewayCode ) ) {
						case 'declined' :
							$message = __( 'Your card was declined.', rcpcommbank()->get_id() );
							break 2;

						case 'expired_card' :
							$message = __( 'Your card is expired.', rcpcommbank()->get_id() );
							break 2;

						case 'timed_out' :
							$message = __( 'The submission timed out. Please try again.', rcpcommbank()->get_id() );
							break 2;
					}

			}

			// redirect with the error message
			$redirect = add_query_arg( array(
				'commbank-error' => empty( $body->result ) ? 'ERROR' : urlencode( $body->result ),
				'message'        => urlencode( $message ),
			), $redirect );

			wp_redirect( $redirect );
			exit;
		}

		// update the payment
		$rcp_payments_db->update( $this->payment->id, array(
			'payment_type' => 'Credit Card One Time',
			'transaction_id' => $body->order->id,
			'status' => 'complete',
		) );

		do_action( 'rcp_gateway_payment_processed', $member, $this->payment->id, $this );

		// log user in if not already logged in
		if ( ! is_user_logged_in() ) {
			rcp_login_user_in( $this->user_id, $this->user_name );
		}

		// redirect to the success page, or error page if something went wrong
		wp_redirect( $this->return_url ); exit;
	}

	/**
	 * Triggers the default RCP functionality then creates and submits CyberSource compatible form
	 *
	 * @since 1.0.0
	 * @return string
	 */
	public function fields() {
		ob_start();
		rcp_get_template_part( 'card-form' );
		return ob_get_clean();
	}

	/**
	 * Validate additional fields during registration submission
	 *
	 * @since  1.0.0
	 */
	public function validate_fields() {
		if ( empty( $_POST['rcp_card_number'] ) ) {
			rcp_errors()->add( 'missing_card_number', __( 'The card number you have entered is invalid', rcpcommbank()->get_id() ), 'register' );
		}

		if ( empty( $_POST['rcp_card_cvc'] ) ) {
			rcp_errors()->add( 'missing_card_code', __( 'The security code you have entered is invalid', rcpcommbank()->get_id() ), 'register' );
		}

		if ( empty( $_POST['rcp_card_zip'] ) ) {
			rcp_errors()->add( 'missing_card_zip', __( 'The zip / postal code you have entered is invalid', rcpcommbank()->get_id() ), 'register' );
		}

		if ( empty( $_POST['rcp_card_name'] ) ) {
			rcp_errors()->add( 'missing_card_name', __( 'The card holder name you have entered is invalid', rcpcommbank()->get_id() ), 'register' );
		}

		if ( empty( $_POST['rcp_card_exp_month'] ) ) {
			rcp_errors()->add( 'missing_card_exp_month', __( 'The card expiration month you have entered is invalid', rcpcommbank()->get_id() ), 'register' );
		}

		if ( empty( $_POST['rcp_card_exp_year'] ) ) {
			rcp_errors()->add( 'missing_card_exp_year', __( 'The card expiration year you have entered is invalid', rcpcommbank()->get_id() ), 'register' );
		}
	}

}